package cs571.mukhar;

public enum Actions {
    ROLL_DICE, PAY_BAIL, DONE, NULL, PAY_RENT, EVAL_PROPERTY, 
    MAKE_BUILD_DECISION, DECLINE_PROPERTY, BUY_PROPERTY, AUCTION_BID, 
    AUCTION_WON, AUCTION_LOST, MAKE_TRADE_DECISION, PROCESS_SPECIAL_ACTION, 
    BUILD_HOUSE, NO_BUILD_HOUSE, BANKRUPT, MAKE_MORTGAGE_DECISION
}
