package cs571.mukhar.states;

public enum Events {
  PLAYER_ACTIVATED_EVENT, AUCTION_STARTED_EVENT, 
  BUILD_OPPORTUNITY_EVENT, ROLL_DICE_EVENT, PAY_BAIL_EVENT, 
  PAY_RENT_EVENT, EVAL_PROPERTY_EVENT, DEVELOP_DECISION_EVENT, 
  BUY_PROPERTY_EVENT, DECLINE_PROPERTY_EVENT, LOST_AUCTION_EVENT, 
  WON_AUCTION_EVENT, TRADE_DECISION_EVENT, 
  PROCESS_SPECIAL_ACTION_EVENT, HANDLE_BANKRUPTCY_EVENT, 
  MORTGAGE_DECISION_EVENT 
}
