package cs571.mukhar;

public enum GameState {
  ACTIVE, AT_NEW_LOCATION, AUCTION, BAIL_PAID, BUILD_PROPERTY, INACTIVE, IN_JAIL, 
  PROPERTY_BOUGHT, PROPERTY_DECLINED, RENT_PAID, TRADE_COMPLETE
}
